/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Arboles;

import java.awt.BorderLayout;
import java.awt.Rectangle;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JInternalFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 *///0968051001------0986335164
public class FrmNuevo extends javax.swing.JDialog {

    private Utilitario u = new Utilitario();
    private SimuladorArbolBinario simulador = new SimuladorArbolBinario();
    private List<Empleado> lista = new ArrayList<>();
    private ModeloTablaPersona modelo = new ModeloTablaPersona();

    /**
     * Creates new form FrmNuevo
     */
    public FrmNuevo(java.awt.Frame parent, boolean modal) throws PropertyVetoException {
        super(parent, modal);
        initComponents();
        jInternalFrame1.add(barra2);
        jInternalFrame1.add(barra1);
        jInternalFrame1.setEnabled(modal);
        jInternalFrame1.getAccessibleContext();
        jInternalFrame1.getLayer();
        estado();
        limpiar();
    }

    public void estado() {
        if (!simulador.estaVacio()) {
            txtEstado.setText("Árbol vacío");
        } else {
            txtEstado.setText("Árbol con elementos");
        }
    }

    public void limpiar() {
        txtApellido.setText(null);
        txtNombre.setText(null);
        txtEdad.setText(null);
        txtBuscar.setText(null);
        txtcedula.setText(null);
        txtdato.setText(null);
        jubilado();
    }

    public void jubilado() {
        modelo.setLista(lista);
        tblJubilados.setModel(modelo);
        tblJubilados.updateUI();
    }

    private void inicializar(boolean enable) {
        this.btnInOrden.setEnabled(enable);
        this.btnPosOrden.setEnabled(enable);
        this.btnPreOrden.setEnabled(enable);
    }

    public void complementos() {
        this.repintarArbol();
    }

    public void buscar() {
        if (!simulador.estaVacio()) {
            if (simulador.buscarNodo(Integer.parseInt(txtBuscar.getText())) == null) {
                JOptionPane.showMessageDialog(null, "Nodo " + txtBuscar.getText() + " no encontrado!", "!Cuidado!", JOptionPane.QUESTION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Nodo " + txtBuscar.getText() + " Encontrado!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio!", "!Cuidado!", JOptionPane.QUESTION_MESSAGE);
        }
    }

    public void eliminar() {
        if (!simulador.estaVacio()) {
            if (simulador.eliminarN(Integer.parseInt(txtBuscar.getText())) == false) {
                JOptionPane.showMessageDialog(null, "Nodo no encontrado!", "!Cuidado!", JOptionPane.QUESTION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "EL Nodo ha sido Eliminado!", "!Nodo Eliminado!", JOptionPane.QUESTION_MESSAGE);
                repintarArbol();
                limpiar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "El arbol esta vacio!", "!Cuidado!", JOptionPane.QUESTION_MESSAGE);
        }
    }

    private void repintarArbol() {
        this.jDesktopPane2.removeAll();
        Rectangle tamaño = this.jInternalFrame1.getBounds();
        this.jInternalFrame1 = null;
        this.jInternalFrame1 = new JInternalFrame("Representación gráfica", true);
        this.jDesktopPane2.add(this.jInternalFrame1, JLayeredPane.DEFAULT_LAYER);
        this.jInternalFrame1.setVisible(true);
        this.jInternalFrame1.setBounds(tamaño);
        this.jInternalFrame1.setEnabled(true);
        this.jInternalFrame1.add(this.simulador.getDibujo(), BorderLayout.CENTER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jDesktopPane2 = new javax.swing.JDesktopPane();
        barra1 = new javax.swing.JScrollBar();
        barra2 = new javax.swing.JScrollBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdato = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        BtnRegistrar = new javax.swing.JButton();
        btnInOrden = new javax.swing.JButton();
        btnPreOrden = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnPosOrden = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        impresion = new javax.swing.JTextArea();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblJubilados = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empleados");
        setBackground(new java.awt.Color(0, 0, 51));
        getContentPane().setLayout(null);

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jDesktopPane2.setBackground(new java.awt.Color(51, 102, 255));
        jDesktopPane2.add(barra1);
        barra1.setBounds(510, 48, 17, 310);

        barra2.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jDesktopPane2.add(barra2);
        barra2.setBounds(0, 348, 510, 20);

        jInternalFrame1.getContentPane().add(jDesktopPane2);
        jDesktopPane2.setBounds(0, -50, 560, 500);

        getContentPane().add(jInternalFrame1);
        jInternalFrame1.setBounds(10, 20, 530, 340);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Años servicio");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(570, 30, 120, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(760, 30, 100, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Apellido");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(760, 90, 100, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Cedula");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(570, 90, 90, 17);

        txtdato.setBackground(new java.awt.Color(51, 102, 255));
        txtdato.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdatoKeyPressed(evt);
            }
        });
        getContentPane().add(txtdato);
        txtdato.setBounds(570, 50, 150, 30);

        txtNombre.setBackground(new java.awt.Color(51, 102, 255));
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(760, 50, 150, 30);

        txtApellido.setBackground(new java.awt.Color(51, 102, 255));
        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(760, 110, 150, 30);

        txtcedula.setBackground(new java.awt.Color(51, 102, 255));
        txtcedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcedulaActionPerformed(evt);
            }
        });
        getContentPane().add(txtcedula);
        txtcedula.setBounds(570, 110, 150, 30);

        BtnRegistrar.setBackground(new java.awt.Color(0, 102, 255));
        BtnRegistrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnRegistrar.setText("Registrar");
        BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(BtnRegistrar);
        BtnRegistrar.setBounds(790, 160, 100, 40);

        btnInOrden.setBackground(new java.awt.Color(0, 102, 255));
        btnInOrden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInOrden.setText("inOrden");
        btnInOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnInOrden);
        btnInOrden.setBounds(580, 330, 90, 30);

        btnPreOrden.setBackground(new java.awt.Color(0, 102, 255));
        btnPreOrden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPreOrden.setText("Preorden");
        btnPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnPreOrden);
        btnPreOrden.setBounds(720, 330, 100, 30);

        btnSalir.setBackground(new java.awt.Color(51, 102, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(870, 593, 140, 50);

        btnPosOrden.setBackground(new java.awt.Color(0, 102, 255));
        btnPosOrden.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnPosOrden.setText("PosOrden");
        btnPosOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPosOrdenActionPerformed(evt);
            }
        });
        getContentPane().add(btnPosOrden);
        btnPosOrden.setBounds(880, 330, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Edad");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(570, 150, 80, 17);

        txtEdad.setBackground(new java.awt.Color(51, 102, 255));
        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEdadKeyPressed(evt);
            }
        });
        getContentPane().add(txtEdad);
        txtEdad.setBounds(570, 170, 150, 30);

        jScrollPane1.setBackground(new java.awt.Color(0, 102, 255));

        impresion.setBackground(new java.awt.Color(51, 102, 255));
        impresion.setColumns(20);
        impresion.setFont(new java.awt.Font("MS Gothic", 2, 14)); // NOI18N
        impresion.setRows(5);
        jScrollPane1.setViewportView(impresion);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(580, 370, 410, 76);

        txtBuscar.setBackground(new java.awt.Color(51, 102, 255));
        txtBuscar.setText("Ingrese años de servicio");
        txtBuscar.setName("buscar"); // NOI18N
        getContentPane().add(txtBuscar);
        txtBuscar.setBounds(680, 210, 140, 30);

        btnBuscar.setBackground(new java.awt.Color(51, 102, 255));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(630, 250, 90, 30);

        btnEliminar.setBackground(new java.awt.Color(0, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(780, 250, 90, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Estado de Arbol");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 460, 130, 30);

        txtEstado.setEditable(false);
        txtEstado.setBackground(new java.awt.Color(51, 102, 255));
        getContentPane().add(txtEstado);
        txtEstado.setBounds(750, 460, 160, 30);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Personas Proximas a Jubilarse", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel1.setLayout(null);

        tblJubilados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblJubilados);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 520, 230);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 380, 540, 260);

        jLabel7.setBackground(new java.awt.Color(51, 102, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Recorridos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(640, 290, 240, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Arboles/Like.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 490, 220, 150);

        setSize(new java.awt.Dimension(1022, 681));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPosOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPosOrdenActionPerformed
//        // TODO add your handling code here:
        String recorrido = null;
        recorrido = this.simulador.postOrden();

        this.impresion.setText("");
        this.impresion.setText(recorrido);
    }//GEN-LAST:event_btnPosOrdenActionPerformed

    private void BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarActionPerformed
        try {
            if (Utilitario.isEmpty(txtcedula.getText()) || Utilitario.isEmpty(txtApellido.getText()) || Utilitario.isEmpty(txtNombre.getText())
                    || Utilitario.isEmpty(txtEdad.getText()) || Utilitario.isEmpty(txtdato.getText())) {
                JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios");
                if (!u.validadorDeCedula(txtcedula.getText())) {
                    JOptionPane.showMessageDialog(this, "Error, verifique cedula");
                    txtcedula.setText(null);
                }
            } else {
                int dato = Integer.parseInt(txtdato.getText());
                String nom = txtNombre.getText();
                String app = txtApellido.getText();
                String ced = null;
                if (Utilitario.validadorDeCedula(txtcedula.getText())) {
                    ced = txtcedula.getText();
                } else {
                    //JOptionPane.showMessageDialog(this, "Cedula Incorrecta");
                    txtcedula.setText(null);
                }

                int edad = Integer.parseInt(txtEdad.getText());
                this.inicializar(true);
                complementos();
                if (this.simulador.insertar(dato, nom, app, ced, edad)) {
                    JOptionPane.showMessageDialog(null, "El dato fue insertado correctamente", " ...", 1);
                    limpiar();
                    if (dato >= 29 || edad >= 59) {
                        lista.add(new Empleado(dato, nom, app, ced, edad));
                    }
                    this.inicializar(true);

                    complementos();
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo insertar el dato", "Intenta de nuevo...", 0);

        }
    }//GEN-LAST:event_BtnRegistrarActionPerformed

    private void btnInOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInOrdenActionPerformed
        String recorrido = null;
        recorrido = this.simulador.inOrden();

        this.impresion.setText("");
        this.impresion.setText(recorrido);
    }//GEN-LAST:event_btnInOrdenActionPerformed

    private void btnPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrdenActionPerformed
        String recorrido = null;
        recorrido = this.simulador.preOrden();

        this.impresion.setText("");
        this.impresion.setText(recorrido);
    }//GEN-LAST:event_btnPreOrdenActionPerformed

    private void txtdatoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdatoKeyPressed
        u.valiarSoloNumeros(txtdato);
    }//GEN-LAST:event_txtdatoKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        u.valiarSoloLetras(txtNombre);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        u.valiarSoloLetras(txtApellido);
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtcedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcedulaActionPerformed

    }//GEN-LAST:event_txtcedulaActionPerformed

    private void txtEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyPressed
        u.valiarSoloNumeros(txtEdad);
    }//GEN-LAST:event_txtEdadKeyPressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmNuevo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmNuevo dialog = null;
                try {
                    dialog = new FrmNuevo(new javax.swing.JFrame(), true);
                } catch (PropertyVetoException ex) {
                    Logger.getLogger(FrmNuevo.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JScrollBar barra1;
    private javax.swing.JScrollBar barra2;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInOrden;
    private javax.swing.JButton btnPosOrden;
    private javax.swing.JButton btnPreOrden;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextArea impresion;
    private javax.swing.JDesktopPane jDesktopPane2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblJubilados;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtdato;
    // End of variables declaration//GEN-END:variables
}
